on:
  push:
    tags:
      - "*"

name:                   Release vsce package
jobs:
  deploy:
    runs-on:            ubuntu-latest
    steps:
      - name:           Checkout
        uses:           actions/checkout@v2
      - name:           Setup build environment (setup node)
        uses:           actions/setup-node@v1
        with:
          node-version: 16
      - name:           Setup build environment (install vsce command)
        run:            npm install -g vsce
      - name:           Create package
        run:            |
                        npm install --include=dev
                        npm install vscode-test
                        vsce package
      - name:           Relase package
        uses:           softprops/action-gh-release@v1
        if:             startsWith(github.ref, 'refs/tags/')
        with:
          files:        '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
